using System.Net;
using System.Security.Cryptography;
using System.Text;
using AuditX.Application.Abstractions.Sanctions;

namespace AuditX.Infrastructure.Sanctions;

/// <summary>
/// Produces the sanctions dossier as a structured, browser-printable HTML artefact (M7). No PDF library is used
/// (license/audit risk — a vetted PDF renderer is a later swap behind <see cref="IDossierGenerator"/>). Evidence is
/// referenced by filename + SHA-256 hash only, never by bytes (US-M7-007). The artefact's own SHA-256 is computed for
/// verifiability (BR-CF-013).
/// </summary>
public sealed class HtmlDossierGenerator : IDossierGenerator
{
    public DossierArtefact Generate(DossierContext context)
    {
        var c = context.Case;
        var sb = new StringBuilder();
        sb.Append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<title>Sanctions Dossier ").Append(Html(c.Id.ToString())).Append("</title>");
        sb.Append("<style>body{font-family:Segoe UI,Arial,sans-serif;margin:2rem;color:#1a1a1a}h1{font-size:1.4rem}h2{font-size:1.1rem;border-bottom:1px solid #ccc;padding-bottom:.25rem;margin-top:1.5rem}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:.4rem .6rem;text-align:left;vertical-align:top}th{width:14rem;background:#f5f5f5}code{font-family:Consolas,monospace}</style>");
        sb.Append("</head><body>");

        sb.Append("<h1>Sanctions Case Dossier</h1>");
        sb.Append("<p>Case <code>").Append(Html(c.Id.ToString())).Append("</code> &mdash; status <strong>")
            .Append(Html(c.Status.ToString())).Append("</strong></p>");

        sb.Append("<h2>Originating exception</h2><table>");
        Row(sb, "Exception id", c.ExceptionId.ToString());
        Row(sb, "Title", context.ExceptionTitle);
        Row(sb, "Severity", context.ExceptionSeverity);
        Row(sb, "Category", context.ExceptionCategory ?? c.Category);
        Row(sb, "Recurrence", c.IsRecurrence ? "Yes" : "No");
        Row(sb, "Subject user id", c.SubjectUserId?.ToString());
        sb.Append("</table>");

        sb.Append("<h2>Recommendation</h2><table>");
        Row(sb, "Recommended sanction", c.Recommendation);
        Row(sb, "Grid version consulted", c.GridConsultedVersion?.ToString());
        Row(sb, "Grid recommended range", c.GridRecommendedRange);
        Row(sb, "Within grid range", c.WithinGridRange ? "Yes" : "No");
        Row(sb, "Deviation reason", c.DeviationReason);
        Row(sb, "Recommended at (UTC)", c.RecommendedAt?.ToString("u"));
        sb.Append("</table>");

        // The dossier reflects the grid version/range that was PINNED on the case at recommendation time
        // (rows above), not the live active grid — which may have changed since.

        sb.Append("<h2>Evidence references (SHA-256)</h2>");
        if (context.EvidenceReferences.Count == 0)
        {
            sb.Append("<p>No evidence files are linked to the originating exception.</p>");
        }
        else
        {
            sb.Append("<table><tr><th>File</th><th>SHA-256</th></tr>");
            foreach (var reference in context.EvidenceReferences)
            {
                sb.Append("<tr><td>").Append(Html(reference.Filename)).Append("</td><td><code>")
                    .Append(Html(reference.Sha256Hash)).Append("</code></td></tr>");
            }

            sb.Append("</table>");
        }

        sb.Append("<hr><p><small>Generated by AuditX. Subject identity is confidential and access-controlled.</small></p>");
        sb.Append("</body></html>");

        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        var sha256 = Convert.ToHexStringLower(SHA256.HashData(bytes));
        return new DossierArtefact(bytes, "text/html", $"sanctions-dossier-{c.Id}.html", sha256);
    }

    private static void Row(StringBuilder sb, string label, string? value)
        => sb.Append("<tr><th>").Append(Html(label)).Append("</th><td>")
            .Append(string.IsNullOrWhiteSpace(value) ? "&mdash;" : Html(value)).Append("</td></tr>");

    private static string Html(string value) => WebUtility.HtmlEncode(value);
}
