using System.Security.Cryptography;
using AuditX.Application.Abstractions.Reports;
using AuditX.Application.Reports.Generation;
using AuditX.Domain.Enums;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using PdfSharp.Fonts;

namespace AuditX.Infrastructure.Reports;

/// <summary>
/// Renders the report as a true, server-generated PDF via PDFsharp/MigraDoc (MIT, pure-managed cross-platform build —
/// no <c>libgdiplus</c>) (M8). Snapshot-faithful: it projects the SAME assembled composition / standalone model the
/// HTML renderer uses (via <see cref="ReportTabularProjection"/>), one heading + table per section, with a title,
/// generated-at line and page footer. Carries its own SHA-256; the canonical/verifiable hash remains the HTML's.
/// </summary>
public sealed class PdfReportRenderer : IReportRenderer
{
    // A4 portrait, 2cm margins → ~17cm of usable content width for the tables.
    private const double UsableWidthCm = 17.0;

    static PdfReportRenderer()
    {
        // The GDI-free build has no built-in font source; register our disk-backed resolver once, process-wide.
        GlobalFontSettings.FontResolver ??= new PdfFontResolver();
    }

    public IReadOnlyCollection<string> SupportedFormats { get; } = ["pdf"];

    public bool CanRender(string format) => string.Equals(format, "pdf", StringComparison.OrdinalIgnoreCase);

    public RenderedArtefact Render(string format, ReportRenderContext context)
    {
        var (title, subtitle) = Header(context);
        var sheets = ReportTabularProjection.From(context);

        var document = BuildDocument(title, subtitle, sheets);

        var renderer = new PdfDocumentRenderer { Document = document };
        renderer.RenderDocument();

        using var stream = new MemoryStream();
        renderer.PdfDocument.Save(stream, false);
        var bytes = stream.ToArray();
        var sha256 = Convert.ToHexStringLower(SHA256.HashData(bytes));
        return new RenderedArtefact(bytes, "application/pdf", $"{ReportArtefactNaming.Stem(context)}.pdf", "pdf", sha256);
    }

    private static (string Title, string Subtitle) Header(ReportRenderContext context)
    {
        if (context.Kind == ReportKind.AuditEngagement && context.Composition is { } c)
        {
            return (c.AuditName, $"Audit report v{c.VersionNumber} — generated {c.GeneratedAtUtc:yyyy-MM-dd} (UTC)");
        }

        return context.Standalone is { } model ? (model.Title, model.Subtitle) : ("Report", string.Empty);
    }

    private static Document BuildDocument(string title, string subtitle, IReadOnlyList<ReportSheet> sheets)
    {
        var document = new Document();
        var normal = document.Styles["Normal"]!;
        normal.Font.Name = PdfFontResolver.FamilyName;
        normal.Font.Size = 9;

        var section = document.AddSection();
        section.PageSetup.PageFormat = PageFormat.A4;
        section.PageSetup.TopMargin = Unit.FromCentimeter(2);
        section.PageSetup.BottomMargin = Unit.FromCentimeter(2);
        section.PageSetup.LeftMargin = Unit.FromCentimeter(2);
        section.PageSetup.RightMargin = Unit.FromCentimeter(2);

        var titleParagraph = section.AddParagraph(title);
        titleParagraph.Format.Font.Size = 16;
        titleParagraph.Format.Font.Bold = true;
        titleParagraph.Format.SpaceAfter = Unit.FromPoint(2);

        if (!string.IsNullOrWhiteSpace(subtitle))
        {
            var subtitleParagraph = section.AddParagraph(subtitle);
            subtitleParagraph.Format.Font.Size = 9;
            subtitleParagraph.Format.Font.Color = Colors.Gray;
            subtitleParagraph.Format.SpaceAfter = Unit.FromPoint(6);
        }

        foreach (var sheet in sheets)
        {
            var heading = section.AddParagraph(sheet.Name);
            heading.Format.Font.Size = 12;
            heading.Format.Font.Bold = true;
            heading.Format.SpaceBefore = Unit.FromPoint(12);
            heading.Format.SpaceAfter = Unit.FromPoint(4);
            AppendTable(section, sheet);
        }

        var footer = section.Footers.Primary.AddParagraph();
        footer.Format.Font.Size = 8;
        footer.Format.Font.Color = Colors.Gray;
        footer.Format.Alignment = ParagraphAlignment.Center;
        footer.AddText("Generated by AuditX · page ");
        footer.AddPageField();
        footer.AddText(" of ");
        footer.AddNumPagesField();

        return document;
    }

    private static void AppendTable(Section section, ReportSheet sheet)
    {
        var table = section.AddTable();
        table.Borders.Width = 0.5;
        table.Borders.Color = Colors.LightGray;

        var columnWidth = Unit.FromCentimeter(UsableWidthCm / Math.Max(1, sheet.Columns.Count));
        foreach (var _ in sheet.Columns)
        {
            table.AddColumn(columnWidth);
        }

        var headerRow = table.AddRow();
        headerRow.Shading.Color = Colors.WhiteSmoke;
        headerRow.Format.Font.Bold = true;
        for (var i = 0; i < sheet.Columns.Count; i++)
        {
            headerRow.Cells[i].AddParagraph(sheet.Columns[i]);
        }

        foreach (var dataRow in sheet.Rows)
        {
            var row = table.AddRow();
            for (var i = 0; i < sheet.Columns.Count; i++)
            {
                row.Cells[i].AddParagraph(i < dataRow.Count ? dataRow[i] ?? string.Empty : string.Empty);
            }
        }
    }
}
