import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Ban,
  Bell,
  BookOpen,
  Bookmark,
  Boxes,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CirclePlay,
  CircleQuestionMark,
  CircleStop,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FilePlus,
  FileText,
  FileUp,
  FlagOff,
  FolderOpen,
  FolderPlus,
  Forward,
  Funnel,
  Gavel,
  Globe,
  GripVertical,
  Hand,
  HardHat,
  History,
  Hourglass,
  House,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  ListPlus,
  ListTodo,
  Lock,
  LogOut,
  type LucideIconData,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  Monitor,
  Moon,
  MousePointerClick,
  Network,
  Package,
  Pencil,
  Play,
  Plus,
  Power,
  Printer,
  RefreshCw,
  Repeat,
  Reply,
  Rocket,
  RotateCcw,
  Save,
  Scale,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Settings,
  ShieldCheck,
  Siren,
  SlidersHorizontal,
  SquarePen,
  Sun,
  SunMoon,
  Timer,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Type,
  Undo2,
  Unlink,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  UserX,
  Users,
  Vote,
  Waypoints,
  Webhook,
  X,
  Zap,
} from 'lucide-angular';

/** Shown when a name isn't mapped — visible enough to flag the gap without breaking layout. */
export const FALLBACK_ICON: LucideIconData = Circle;

/**
 * Maps the legacy Material Symbols names used across AuditX templates to their Lucide equivalents.
 * The app-icon wrapper resolves names through this table, so call sites keep their familiar Material
 * names and the whole app switches to Lucide's outline set from one place.
 */
export const MATERIAL_TO_LUCIDE: Readonly<Record<string, LucideIconData>> = {
  account_balance: Landmark,
  account_tree: Network,
  ads_click: MousePointerClick,
  analytics: ChartColumn,
  add: Plus,
  apps: LayoutGrid,
  assignment_turned_in: ClipboardCheck,
  add_link: Link2,
  admin_panel_settings: ShieldCheck,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_drop_down: ChevronDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment: ClipboardList,
  badge: BadgeCheck,
  balance: Scale,
  block: Ban,
  bolt: Zap,
  bookmark: Bookmark,
  bookmarks: Bookmark,
  cancel: CircleX,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  clear: X,
  close: X,
  content_copy: Copy,
  create_new_folder: FolderPlus,
  crisis_alert: Siren,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delete_outline: Trash,
  delete_sweep: Trash2,
  description: FileText,
  desktop_windows: Monitor,
  done: Check,
  donut_large: ChartPie,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  edit_calendar: CalendarDays,
  edit_note: SquarePen,
  engineering: HardHat,
  error_outline: CircleAlert,
  event: CalendarDays,
  event_available: CalendarCheck,
  event_note: CalendarClock,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  filter_alt: Funnel,
  first_page: ChevronsLeft,
  flag_off: FlagOff,
  folder_open: FolderOpen,
  format_size: Type,
  forward: Forward,
  gavel: Gavel,
  grid_on: LayoutGrid,
  grid_view: LayoutGrid,
  group: Users,
  groups: Users,
  help_outline: CircleQuestionMark,
  history: History,
  home: House,
  hourglass_top: Hourglass,
  how_to_reg: UserCheck,
  how_to_vote: Vote,
  hub: Waypoints,
  inbox: Inbox,
  insights: Lightbulb,
  inventory: Package,
  inventory_2: Boxes,
  key: KeyRound,
  language: Globe,
  light_mode: Sun,
  lightbulb: Lightbulb,
  last_page: ChevronsRight,
  leaderboard: Trophy,
  link: Link,
  link_off: Unlink,
  list: List,
  list_alt: List,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  menu: Menu,
  menu_book: BookOpen,
  more_vert: EllipsisVertical,
  network_check: Network,
  note_add: FilePlus,
  notifications: Bell,
  open_in_new: ExternalLink,
  outgoing_mail: Send,
  pending_actions: ListTodo,
  person: User,
  person_add: UserPlus,
  person_off: UserX,
  person_search: UserSearch,
  picture_as_pdf: FileText,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_add: ListPlus,
  power_settings_new: Power,
  print: Printer,
  publish: Upload,
  rate_review: MessageSquare,
  refresh: RefreshCw,
  repeat: Repeat,
  replay: RotateCcw,
  reply: Reply,
  report_problem: TriangleAlert,
  rocket_launch: Rocket,
  rule: ListChecks,
  save: Save,
  schedule: Clock,
  schedule_send: SendHorizontal,
  search: Search,
  segment: List,
  send: Send,
  settings: Settings,
  space_dashboard: LayoutDashboard,
  stop_circle: CircleStop,
  summarize: ScrollText,
  swap_horiz: ArrowLeftRight,
  task_alt: CircleCheckBig,
  timer: Timer,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  unarchive: ArchiveRestore,
  undo: Undo2,
  unfold_more: ChevronsUpDown,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  waving_hand: Hand,
  webhook: Webhook,
  widgets: LayoutGrid,
  brightness_auto: SunMoon,
};
