using System.Net;
using System.Security.Cryptography;
using System.Text;
using AuditX.Application.Abstractions.Ac;
using AuditX.Application.Ac.Generation;

namespace AuditX.Infrastructure.Ac;

/// <summary>
/// Renders the CANONICAL, hashed, browser-printable AC pack as structured HTML (M13). Mirrors the M8
/// <c>HtmlReportRenderer</c>: <see cref="WebUtility.HtmlEncode"/> on all dynamic text. The sanctions section is
/// rendered from the AGGREGATE-only composition (no subject identity). The artefact's SHA-256 is computed over the
/// exact stored bytes (no post-hash substitution) so verify-on-read recomputes identically.
/// </summary>
public sealed class HtmlAcPackRenderer : IAcPackRenderer
{
    public IReadOnlyCollection<string> SupportedFormats { get; } = ["html"];

    public bool CanRender(string format) => string.Equals(format, "html", StringComparison.OrdinalIgnoreCase);

    public AcRenderedArtefact Render(string format, AcPackRenderContext context)
    {
        var c = context.Composition;
        var sb = new StringBuilder();
        sb.Append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<title>Audit Committee Pack — v").Append(c.VersionNumber).Append("</title>");
        sb.Append("<style>body{font-family:Segoe UI,Arial,sans-serif;margin:2rem;color:#1a1a1a}h1{font-size:1.5rem}h2{font-size:1.15rem;border-bottom:1px solid #ccc;padding-bottom:.25rem;margin-top:1.5rem}table{border-collapse:collapse;width:100%;margin-top:.5rem}td,th{border:1px solid #ccc;padding:.4rem .6rem;text-align:left;vertical-align:top}th{background:#f5f5f5}.meta th{width:16rem}</style>");
        sb.Append("</head><body>");

        // Cover
        sb.Append("<h1>Audit Committee Pack</h1>");
        sb.Append("<table class=\"meta\">");
        Row(sb, "Pack version", c.VersionNumber.ToString());
        Row(sb, "Reporting period", $"{c.PeriodStart:yyyy-MM-dd} to {c.PeriodEnd:yyyy-MM-dd}");
        if (!string.IsNullOrWhiteSpace(c.AcMeetingLabel))
        {
            Row(sb, "Meeting", c.AcMeetingLabel);
        }

        Row(sb, "Generated (UTC)", c.GeneratedAtUtc.ToString("u"));
        Row(sb, "Integrity (SHA-256)", "Computed at issue — verify via the pack's download header / verify-on-read.");
        sb.Append("</table>");

        if (!string.IsNullOrWhiteSpace(context.CiaSupplementaryText))
        {
            sb.Append("<h2>Chief Internal Auditor narrative</h2><p>").Append(Html(context.CiaSupplementaryText)).Append("</p>");
        }

        AppendPlanStatus(sb, c);
        AppendExceptionPortfolio(sb, c);
        AppendMaterialFindings(sb, c);
        AppendSanctionsConsistency(sb, c);
        AppendRecurrenceClusters(sb, c);

        sb.Append("<hr><p><small>Generated by AuditX. Sanctions data is aggregated by business unit; subject identities are omitted.</small></p>");
        sb.Append("</body></html>");

        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        var sha256 = Convert.ToHexStringLower(SHA256.HashData(bytes));
        return new AcRenderedArtefact(bytes, "text/html", $"ac-pack-v{c.VersionNumber}.html", "html", sha256);
    }

    private static void AppendPlanStatus(StringBuilder sb, AcPackComposition c)
    {
        sb.Append("<h2>Plan status</h2><table>");
        Row(sb, "Plans", c.TotalPlans.ToString());
        Row(sb, "Plan items", c.PlanItemsTotal.ToString());
        Row(sb, "Completed", c.PlanItemsCompleted.ToString());
        Row(sb, "Completion", $"{c.PlanCompletionPercent}%");
        sb.Append("</table>");
    }

    private static void AppendExceptionPortfolio(StringBuilder sb, AcPackComposition c)
    {
        sb.Append("<h2>Exception portfolio</h2><table>");
        Row(sb, "Open exceptions", c.OpenExceptionTotal.ToString());
        Row(sb, "Average closure (days)", c.AverageClosureDays?.ToString("0.0") ?? "—");
        sb.Append("</table>");
        if (c.ExceptionsBySeverity.Count > 0)
        {
            sb.Append("<table><tr><th>Severity</th><th>Open</th></tr>");
            foreach (var s in c.ExceptionsBySeverity)
            {
                sb.Append("<tr><td>").Append(Html(s.Severity)).Append("</td><td>").Append(s.Count).Append("</td></tr>");
            }

            sb.Append("</table>");
        }
    }

    private static void AppendMaterialFindings(StringBuilder sb, AcPackComposition c)
    {
        sb.Append("<h2>Material findings</h2>");
        if (c.MaterialFindings.Count == 0)
        {
            sb.Append("<p>No Critical or High open findings.</p>");
            return;
        }

        sb.Append("<table><tr><th>Title</th><th>Severity</th><th>Status</th><th>Raised</th><th>Target</th></tr>");
        foreach (var f in c.MaterialFindings)
        {
            sb.Append("<tr><td>").Append(Html(f.Title)).Append("</td><td>").Append(Html(f.Severity))
                .Append("</td><td>").Append(Html(f.Status)).Append("</td><td>").Append(f.RaisedAt.ToString("yyyy-MM-dd"))
                .Append("</td><td>").Append(f.TargetDate.ToString("yyyy-MM-dd")).Append("</td></tr>");
        }

        sb.Append("</table>");
    }

    private static void AppendSanctionsConsistency(StringBuilder sb, AcPackComposition c)
    {
        sb.Append("<h2>Sanctions consistency (aggregate)</h2><table>");
        Row(sb, "Total cases", c.SanctionsTotalCases.ToString());
        Row(sb, "Grid adherence", $"{c.SanctionsGridAdherencePercent}%");
        Row(sb, "Appeal rate", $"{c.SanctionsAppealRatePercent}%");
        sb.Append("</table>");
        if (c.SanctionsByBusinessUnit.Count > 0)
        {
            sb.Append("<table><tr><th>Business unit</th><th>Cases</th><th>Within grid</th><th>Adherence</th><th>Deviations</th><th>Appeals</th></tr>");
            foreach (var r in c.SanctionsByBusinessUnit)
            {
                sb.Append("<tr><td>").Append(Html(r.BusinessUnit)).Append("</td><td>").Append(r.CaseCount)
                    .Append("</td><td>").Append(r.WithinGridCount).Append("</td><td>").Append(r.GridAdherencePercent).Append('%')
                    .Append("</td><td>").Append(r.DeviationCount).Append("</td><td>").Append(r.AppealCount).Append("</td></tr>");
            }

            sb.Append("</table>");
        }
    }

    private static void AppendRecurrenceClusters(StringBuilder sb, AcPackComposition c)
    {
        sb.Append("<h2>Recurrence clusters</h2>");
        if (c.RecurrenceClusters.Count == 0)
        {
            sb.Append("<p>No recurring control weaknesses detected.</p>");
            return;
        }

        sb.Append("<table><tr><th>Entity</th><th>Category</th><th>Closed exceptions</th><th>Window (months)</th></tr>");
        foreach (var rc in c.RecurrenceClusters)
        {
            sb.Append("<tr><td>").Append(Html(rc.AuditableEntityId.ToString())).Append("</td><td>").Append(Html(rc.Category ?? "—"))
                .Append("</td><td>").Append(rc.ClosedExceptionCount).Append("</td><td>").Append(rc.WindowMonths).Append("</td></tr>");
        }

        sb.Append("</table>");
    }

    private static void Row(StringBuilder sb, string label, string? value)
        => sb.Append("<tr><th>").Append(Html(label)).Append("</th><td>")
            .Append(string.IsNullOrWhiteSpace(value) ? "&mdash;" : Html(value)).Append("</td></tr>");

    private static string Html(string value) => WebUtility.HtmlEncode(value);
}
